######################################################################
# Automatically generated by qmake (3.0) ?? 5? 15 15:02:44 2013
######################################################################

QT += core gui
QT += network
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = qweather
INCLUDEPATH += .

# Input
HEADERS += jsonclient.h weatherinfo.h weatherwin.h
SOURCES += jsonclient.cpp main.cpp weatherinfo.cpp weatherwin.cpp